### ISSUE TITLE
vue-router 中的 base 需要可配置

### ISSUE THREAD

**Issue by miomio-xiao** [IDuxFE/archive#54]
https://github.com/IDuxFE/archive/blob/fc920f2d2a0bf20f7cc73c9b84f2857e1e98d775/packages/archive-app/src/mount/mountApp.ts#L67

现在固定死了 `/` 导致部署会有问题

**Comment by miomio-xiao** [comment]
https://github.com/IDuxFE/archive/blob/fc920f2d2a0bf20f7cc73c9b84f2857e1e98d775/packages/archive-app/src/resolveThemeOptions.ts#L28C17-L28C17

这个需不需要同步改一下

**Comment by sallerli1** [comment]
已修复，现在默认会使用vite.config.js中的base，archive.config.js里可以配置baseUrl
